version: "1"
services:
  backend:
    image: "amnasalahudin/backend"
    ports:
     - "3001:3001"
    networks:
     - scd-frontbackend
  frontend:
     image: "amnasalahudin/frontendfinal:v1"
     stdin_open: true
     ports:
       - "3000:3000"
     depends_on:
       - backend
     networks:
       - scd-frontbackend

networks:
  scd-frontbackend:
    driver: bridge


     